---
version: "3.8"
services:
  pyhabot:
    container_name: pyhabot
    build: .
    environment:
      - PYHABOT_INTEGRATION=telegram
      - DISCORD_TOKEN= # csak ha a 'docker'-t választjuk, mint integráció
      - TELEGRAM_TOKEN= # csak ha a 'telegram'-ot választjuk, mint integráció
      - PASTEBIN_API_KEY= # opcionális
    restart: unless-stopped
